<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>scriban</string>
	</array>
	<key>name</key>
	<string>Scriban</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literals</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bool-literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>keyword.bool.scriban</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>##</string>
					<key>end</key>
					<string>(?=}})|##</string>
					<key>name</key>
					<string>comment.block.scriban</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^\s+)?(?=#)</string>
					<key>end</key>
					<string>(?=~?}}|$)</string>
					<key>name</key>
					<string>comment.line.scriban</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>match</key>
			<string>\b(func|end|if|else|for|break|continue|in|while|capture|readonly|import|with|wrap|include|ret|case|when|this|empty|tablerow)\b</string>
			<key>name</key>
			<string>keyword.type.scriban</string>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#numeric-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bool-literal</string>
				</dict>
			</array>
		</dict>
		<key>numeric-literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b([0-9]+)?\.[0-9]+((e|E)[0-9]+)?\b</string>
					<key>name</key>
					<string>constant.numeric.decimal.scriban</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[0-9]+(e|E)[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.decimal.scriban</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.decimal.scriban</string>
				</dict>
			</array>
		</dict>
		<key>string-literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>('|")</string>
					<key>end</key>
					<string>\1</string>
					<key>name</key>
					<string>string.quoted.double.scriban</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.scriban</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>end</key>
					<string>`</string>
					<key>name</key>
					<string>string.quoted.double.scriban</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>``</string>
							<key>name</key>
							<string>constant.character.escape.scriban</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.scriban</string>
	<key>uuid</key>
	<string>f7870e1f-dfab-4130-91ba-22e786365910</string>
</dict>
</plist>
