<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Scriban-CSharp</string>
    <key>scopeName</key>
    <string>source.cs.scriban</string>
    <key>fileTypes</key>
    <array>
      <string>scriban-csharp</string>
    </array>
    <key>uuid</key>
    <string>87b709df-3e98-466e-bbac-f437bde7ba35</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>source.cs#preprocessor</string>
      </dict>
      <dict>
        <key>include</key>
        <string>source.cs#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>source.cs#literal</string>
      </dict>
      <dict>
        <key>include</key>
        <string>source.cs#storage-modifier</string>
      </dict>
      <dict>
        <key>include</key>
        <string>source.cs#type-builtin</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(namespace)\s+([\w\.]+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(using)\s+([\w\.]+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.using</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(class|struct|interface|enum)\s+(\w+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>\bcase\b</string>
        <key>name</key>
        <string>keyword.control.case.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\belse\b</string>
        <key>name</key>
        <string>keyword.control.conditional.else.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bif\b</string>
        <key>name</key>
        <string>keyword.control.conditional.if.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bdefault\b</string>
        <key>name</key>
        <string>keyword.control.default.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bbreak\b</string>
        <key>name</key>
        <string>keyword.control.flow.break.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bcontinue\b</string>
        <key>name</key>
        <string>keyword.control.flow.continue.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\breturn\b</string>
        <key>name</key>
        <string>keyword.control.flow.return.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bthrow\b</string>
        <key>name</key>
        <string>keyword.control.flow.throw.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\byield\b</string>
        <key>name</key>
        <string>keyword.control.flow.yield.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bgoto\b</string>
        <key>name</key>
        <string>keyword.control.goto.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bdo\b</string>
        <key>name</key>
        <string>keyword.control.loop.do.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bfor\b</string>
        <key>name</key>
        <string>keyword.control.loop.for.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bforeach\b</string>
        <key>name</key>
        <string>keyword.control.loop.foreach.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bin\b</string>
        <key>name</key>
        <string>keyword.control.loop.in.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bwhile\b</string>
        <key>name</key>
        <string>keyword.control.loop.while.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bswitch\b</string>
        <key>name</key>
        <string>keyword.control.switch.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bcatch\b</string>
        <key>name</key>
        <string>keyword.control.try.catch.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\btry\b</string>
        <key>name</key>
        <string>keyword.control.try.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bfinally\b</string>
        <key>name</key>
        <string>keyword.control.try.finally.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bwhen\b</string>
        <key>name</key>
        <string>keyword.control.try.when.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\badd\b</string>
        <key>name</key>
        <string>keyword.other.add.cs,</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\balias\b</string>
        <key>name</key>
        <string>keyword.other.alias.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bas\b</string>
        <key>name</key>
        <string>keyword.other.as.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bawait\b</string>
        <key>name</key>
        <string>keyword.other.await.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bawait\b</string>
        <key>name</key>
        <string>keyword.other.await.cs,</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bbase\b</string>
        <key>name</key>
        <string>keyword.other.base.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bchecked\b</string>
        <key>name</key>
        <string>keyword.other.checked.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bclass\b</string>
        <key>name</key>
        <string>keyword.other.class.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bclass\b</string>
        <key>name</key>
        <string>keyword.other.class.cs,</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bdefault\b</string>
        <key>name</key>
        <string>keyword.other.default.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bdelegate\b</string>
        <key>name</key>
        <string>keyword.other.delegate.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\benum\b</string>
        <key>name</key>
        <string>keyword.other.enum.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bevent\b</string>
        <key>name</key>
        <string>keyword.other.event.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bexplicit\b</string>
        <key>name</key>
        <string>keyword.other.explicit.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bextern\b</string>
        <key>name</key>
        <string>keyword.other.extern.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bget\b</string>
        <key>name</key>
        <string>keyword.other.get.cs,</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bimplicit\b</string>
        <key>name</key>
        <string>keyword.other.implicit.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\binterface\b</string>
        <key>name</key>
        <string>keyword.other.interface.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bis\b</string>
        <key>name</key>
        <string>keyword.other.is.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\block\b</string>
        <key>name</key>
        <string>keyword.other.lock.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bnameof\b</string>
        <key>name</key>
        <string>keyword.other.nameof.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bnew\b</string>
        <key>name</key>
        <string>keyword.other.new.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bremove\b</string>
        <key>name</key>
        <string>keyword.other.remove.cs,</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bset\b</string>
        <key>name</key>
        <string>keyword.other.set.cs,</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bstatic\b</string>
        <key>name</key>
        <string>keyword.other.static.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bstruct\b</string>
        <key>name</key>
        <string>keyword.other.struct.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bstruct\b</string>
        <key>name</key>
        <string>keyword.other.struct.cs,</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bthis\b</string>
        <key>name</key>
        <string>keyword.other.this.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\btypeof\b</string>
        <key>name</key>
        <string>keyword.other.typeof.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bunchecked\b</string>
        <key>name</key>
        <string>keyword.other.unchecked.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\busing\b</string>
        <key>name</key>
        <string>keyword.other.using.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bvar\b</string>
        <key>name</key>
        <string>keyword.other.var.cs</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\bwhere\b</string>
        <key>name</key>
        <string>keyword.other.where.cs</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>({{[~\-]?)</string>
        <key>end</key>
        <string>([~\-]?}})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>invalid.strong</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>invalid.strong</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
            <key>match</key>
            <string>\b(func|end|if|else|for|break|continue|in|while|capture|readonly|import|with|wrap|include|ret|case|when|this|empty|tablerow)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.function
match: \b(true|false)\b</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.scriban</string>
          </dict>
        </array>
      </dict>
    </array>
  </dict>
</plist>