<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Scriban-Html</string>
    <key>scopeName</key>
    <string>text.html.scriban</string>
    <key>fileTypes</key>
    <array>
      <string>scriban-html</string>
    </array>
    <key>uuid</key>
    <string>2A3B4DD2-561E-4662-A83B-8E3A15E26315</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>comment.block.scriban</string>
        <key>begin</key>
        <string>{(%+){[~\-]?</string>
        <key>end</key>
        <string>[~\-]?}\1}</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>invalid</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>invalid</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>language.script.scriban</string>
        <key>begin</key>
        <string>({{[~\-]?)</string>
        <key>end</key>
        <string>([~\-]?}})</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>invalid</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>invalid</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
            <key>match</key>
            <string>\b(func|end|if|else|for|break|continue|in|while|capture|readonly|import|with|wrap|include|ret|case|when|this|empty|tablerow)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.function
match: \b(true|false)\b</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.scriban</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>include</key>
        <string>text.html.basic</string>
      </dict>
    </array>
  </dict>
</plist>