<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Scriban-txt</string>
    <key>scopeName</key>
    <string>text.scriban</string>
    <key>fileTypes</key>
    <array>
      <string>scriban-txt</string>
    </array>
    <key>uuid</key>
    <string>46D6F82D-7128-47BF-987D-B9671D2F08AA</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>comment.block.scriban</string>
        <key>begin</key>
        <string>{(%+){[~\-]?</string>
        <key>end</key>
        <string>[~\-]?}\1}</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>invalid</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>invalid</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>language.script.scriban</string>
        <key>begin</key>
        <string>({{[~\-]?)</string>
        <key>end</key>
        <string>([~\-]?}})</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>invalid</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>invalid</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.scriban</string>
          </dict>
        </array>
      </dict>
    </array>
  </dict>
</plist>